server:
  port: 8000
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shashank915/kt-session-microservices-configuration
          search-paths: client-1

